import Providers from "./components/Providers";
import Navbar from "./components/Navbar";
import "./globals.css";
import Footer from "./components/Footer";


export const metadata = {
  title: "e commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen max-w-[1500px]">
        <Providers>
          <Navbar />
          <main className="">
            {/* Wrap in SlowServer to simulate server delay and show loading UI */}

            {children}

          </main>
          <Footer />
        </Providers>

      </body>
    </html>
  );
}
