import Providers from "./components/Providers";
import Navbar from "./components/Navbar";
import "./globals.css";
import Footer from "./components/Footer";

export const metadata = {
  title: "e commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50">
        <Providers>
          <Navbar/> 
          <main className="pt-32">
            {children}
          </main> 
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
